FROM node:22-alpine

WORKDIR /app

# что копируем, куда копируем
COPY . .

CMD [ "node", "app.js" ]

# Команда для создания образа:
# docker build -t console-log-app .
#  console-log-app - название image
# точка это путь до докерфайлаdocker